equinor/fmu-sumo

src/fmu/sumo/uploader/_fileondisk.py

Solve #60 
Note that most of the diff is `black` formatting.

add missing argument to _delete_metadata()

---

src/fmu/sumo/uploader/_caseondisk.py
src/fmu/sumo/uploader/_fileondisk.py

Solving #24 but also bundling in some other things in the same go

24 unnecessary warning

---

src/fmu/sumo/uploader/_caseondisk.py
src/fmu/sumo/uploader/_connection.py
src/fmu/sumo/uploader/_fileondisk.py
tests/test_uploader.py

In this PR, the uploader is shifted from using `CallSumoApi` to `SumoClient`.

Use SumoClient for uploader

---

src/fmu/sumo/uploader/__init__.py
src/fmu/sumo/uploader/_caseonjob.py
src/fmu/sumo/uploader/_connection.py
src/fmu/sumo/uploader/_fileonjob.py

Support for bulk aggregation service, it has been used for a while by the upload job of the bulk aggregation service. It is not refactored, but does not conflict with the existing uploader for case on disk.

Aggregations

---

src/fmu/sumo/explorer/_document_collection.py
src/fmu/sumo/explorer/_utils.py

data.time has changed from a list of objects, to a nested object. Update definition of dynamic fields to handle both cases.

data.time.fix

---

src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/child.py
src/fmu/sumo/explorer/objects/child_collection.py
src/fmu/sumo/explorer/objects/document_collection.py
src/fmu/sumo/explorer/objects/polygons.py
src/fmu/sumo/explorer/objects/surface.py
src/fmu/sumo/explorer/objects/table.py

- Handle arrow files (returned as pd.DataFrame)
- More type hints
- Document sorting bug fix

Handle arrow files

---

examples/explorer.ipynb
src/fmu/sumo/explorer/__init__.py
src/fmu/sumo/explorer/objects/child_collection.py
src/fmu/sumo/explorer/objects/document_collection.py
src/fmu/sumo/explorer/objects/polygons_collection.py
src/fmu/sumo/explorer/objects/surface.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table_collection.py
src/fmu/sumo/explorer/timefilter.py
src/fmu/sumo/explorer/utils.py
tests/data/test_case_080/.seismic.segy.yml
tests/data/test_case_080/.surface.bin.yml
tests/data/test_case_080/.surface_error.bin.yml

New `TimeFilter` class and `time` parameter in `SurfaceCollection.filter` method.
Get time info:
```python
case.surfaces.timestamps
case.surfaces.intervals
```
Construct time filter:
```python
from fmu.sumo.explorer import TimeFilter, TimeType
time = TimeFilter(type=TimeType.TIMESTAMP)
time = TimeFilter(type=TimeType.TIMESTAMP, start="2018-01-01", end="2022-01-01")
time = TimeFilter(type=TimeType.INTERVAL)
time = TimeFilter(type=TimeType.INTERVAL, start="2018-01-01", end="2022-01-01")
time = TimeFilter(type=TimeType.INTERVAL, start="2018-01-01", end="2022-01-01", exact=True)
time = TimeFilter(type=TimeType.INTERVAL, start="2018-01-01", end="2022-01-01", overlap=True)
time = TimeFilter(type=TimeType.ALL)
time = TimeFilter(type=TimeType.NONE)
```
Apply time filter:
```python
surfs = …
```

Time filtering and bool parameters

---

examples/explorer.ipynb
src/fmu/sumo/explorer/contexts/observation.py
src/fmu/sumo/explorer/contexts/realization.py
src/fmu/sumo/explorer/objects/child.py
src/fmu/sumo/explorer/objects/child_collection.py
src/fmu/sumo/explorer/objects/document_collection.py
src/fmu/sumo/explorer/objects/polygons_collection.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table_collection.py

I have changed iteration ids to iteration names. Now it is showing iteration names when I test it though command "surfs.iterations". Hopefully that would be expected change.

changed iteration id to iteration name

---

src/fmu/sumo/explorer/objects/document_collection.py
src/fmu/sumo/explorer/objects/surface.py

add bbox and spec property to Surface

---

src/fmu/sumo/explorer/objects/child_collection.py
src/fmu/sumo/explorer/objects/table_collection.py

Add `column` parameter to `TableCollection.filter` + `columns` property on `TableCollection`

TableCollection column filter

---

src/fmu/sumo/explorer/_utils.py
src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_child.py
src/fmu/sumo/explorer/objects/_child_collection.py
src/fmu/sumo/explorer/objects/_document_collection.py
src/fmu/sumo/explorer/objects/case_collection.py

Added the following methods:
- `Explorer.get_case_by_uuid`
- `Explorer.get_surface_by_uuid`
- `Explorer.get_polygons_by_uuid`
- `Explorer.get_table_by_uuid`
closes #128

Add methods to Explorer class to get objects by uuid

---

docs/explorer.rst

Added the "Usage and examples" section for Explorer
https://fmu-sumo.readthedocs.io/en/latest/explorer.html# is currently building from this branch so the changes can be previewed here. Will change back to master when this is merged.

Explorer docs

---

.github/workflows/build_docs.yaml
.github/workflows/run_tests.yaml
examples/explorer.ipynb
examples/tables.ipynb
src/fmu/sumo/explorer/__init__.py
src/fmu/sumo/explorer/_utils.py
src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_child.py
src/fmu/sumo/explorer/objects/_child_collection.py
src/fmu/sumo/explorer/objects/_document.py
src/fmu/sumo/explorer/objects/_document_collection.py
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/case_collection.py
src/fmu/sumo/explorer/objects/polygons.py
src/fmu/sumo/explorer/objects/polygons_collection.py
src/fmu/sumo/explorer/objects/surface.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table.py
src/fmu/sumo/explorer/objects/table_aggregated.py
src/fmu/sumo/explorer/objects/table_collection.py
src/fmu/sumo/explorer/pit.py
src/fmu/sumo/explorer/timefilter.py
tests/test_aggregated_table.py
tests/test_explorer.py

Add functionality for working with aggregated tables
* Separate class AggregatedTable
* functionality for easy access to metadata for aggregated objects

Aggregated focus

---

src/fmu/sumo/uploader/scripts/sumo_upload.py

https://fmu-docs.equinor.com/docs/ert/experimental/plugin_system.html#forward-model-documentation

Try to populate fmu-docs ert plugin documentation

---

src/fmu/sumo/explorer/objects/cube.py
src/fmu/sumo/uploader/_fileondisk.py
tests/test_uploader.py

Change url logic in the Cube class as the sumo-core `authuri` behavior has changed

Seismic url

---

src/fmu/sumo/explorer/objects/cube_collection.py
src/fmu/sumo/uploader/_fileondisk.py

* Allow filtering cubes on `fmu.context.stage`
* Handle new blob authuri format (`/container/object_id`) when doing SEGYImport -> fixes failing test

add stage to CubeCollection filter

---

src/fmu/sumo/explorer/objects/_child_collection.py

Expose data.content and file.checksum_md5 as metadata

---

.github/workflows/build_docs.yaml
.github/workflows/publish_release.yaml
.github/workflows/run_tests.yaml
requirements/requirements_docs.txt
setup.py

Had to pin `sphinx==6.2.1` to fix`build_docs` workflow failing.
Bug created in DevOps board [386548](https://dev.azure.com/Equinor/Sumo/_sprints/taskboard/Sudo%20Team/Sumo/Sprint%2055%20-%20Summersprint?workitem=386548)

Pypi publishing workflow

---

setup.py
src/fmu/sumo/explorer/_utils.py
src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_child.py
src/fmu/sumo/explorer/objects/_child_collection.py
src/fmu/sumo/explorer/objects/_document_collection.py
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/case_collection.py
src/fmu/sumo/explorer/objects/cube.py
src/fmu/sumo/explorer/objects/cube_collection.py
src/fmu/sumo/explorer/objects/polygons.py
src/fmu/sumo/explorer/objects/surface.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table.py
src/fmu/sumo/explorer/objects/table_aggregated.py
src/fmu/sumo/explorer/objects/table_collection.py
tests/test_aggregated_table.py

* add `_async` versions of all methods that directly or indirectly use the Sumo api
depends on [wrapper update](https://github.com/equinor/sumo-wrapper-python/pull/139)

Async support

---

examples/tables.ipynb

Make tables noetbook more complete, with more data, and examples

Add better explanations to tables.ipynb

---

requirements/requirements.txt
tests/test_utility_sim2sumo.py

(Was not able to exclude windows on the parametrize thingy that calls sim2sumo, so the test_utility_sim2sumo.py file is indented from line 13)

Do not import ert/ecl2df on windows. Do not run sim2sumo tests on windows

---

src/fmu/sumo/explorer/objects/surface_collection.py

Update url used by surface aggregation to match change in Sumo core.
Solves #232

update surface aggregation url

---

.github/workflows/run_tests_access_drogon_manage_login.yaml
.github/workflows/run_tests_access_drogon_read_login.yaml
.github/workflows/run_tests_access_drogon_write_login.yaml
.github/workflows/run_tests_access_no_access_login.yaml
tests/test_access/README.md
tests/test_access/tst_access_drogon_manage_login.py
tests/test_access/tst_access_drogon_read_login.py
tests/test_access/tst_access_drogon_write_login.py
tests/test_access/tst_access_no_access_login.py

[_Link to the issue resolved by this PR._](https://github.com/orgs/equinor/projects/517/views/2?sliceBy%5Bvalue%5D=roywilly&pane=issue&itemId=51867183)

Add tests for bulk aggregation

---

.github/workflows/run_tests_access_drogon_manage_sharedkey.yaml
.github/workflows/run_tests_access_drogon_read_sharedkey.yaml
.github/workflows/run_tests_access_drogon_write_sharedkey.yaml
tests/test_access/README.md
tests/test_access/tst_access_drogon_manage_login.py

https://github.com/orgs/equinor/projects/517/views/2?sliceBy%5Bvalue%5D=roywilly&pane=issue&itemId=51867183

Add access tests using shared-key for auth

---

tests/test_access/tst_access_drogon_manage_login.py
tests/test_access/tst_access_drogon_write_login.py

Fix nightly tests, handle changed response json

---

tests/test_access/tst_access_drogon_manage_login.py
tests/test_access/tst_access_drogon_read_login.py
tests/test_access/tst_access_drogon_write_login.py

Fix nightly tests by finding a case which has iterations and surfaces

---

.github/workflows/run_tests_access_drogon_read_login.yaml
.github/workflows/run_tests_access_drogon_write_login.yaml

(Is it due to some radix nightly job?)

New time for nightly tests that fail several times every week with 500 error

---

.github/workflows/run_tests.yaml

https://github.com/actions/setup-python/issues/850

Fix nightly tests that fail for mac os

---

tests/test_access/README.md
tests/test_access/tst_access_drogon_affiliate_login.py

and fix a couple of other affilate tests

Add test for delete objects by an affiliate

---

src/fmu/sumo/explorer/objects/surface_collection.py

Use new aggregation endpoint for surface aggregation.

Use new endpoint for surface aggregation

---

src/fmu/sumo/explorer/objects/_search_context.py

Reported by Webviz team, on slack.
Duplicate existing methods, and modify them for asynchronous use.
Note: this is not ideal... we should consider whether we can implement just the asynchronous versions of the methods, and call them from sync code.

feat: add methods for async aggregation.

---

src/fmu/sumo/explorer/objects/_search_context.py

Closes #367 
Use the support function `_get_object_by_class_and_uuid`, since this is exactly what it is meant for.

fix: corrections for get_{surface,table,polygons}_by_uuid and async equivalents

---

src/fmu/sumo/explorer/objects/dictionary.py

- need to call .read() to get blob content as bytes in Dictionary.parse()
- added sync version .parse_async().

fix: Dictionary.parse/parse_async

---

src/fmu/sumo/explorer/objects/__init__.py
src/fmu/sumo/explorer/objects/_search_context.py

- Ensure that requested aggregation matches the set of realizations. 
- Also, ensure that exactly one column is specified for table aggregation.

fix: more robust table aggregations

---

.gitignore
src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_child.py
src/fmu/sumo/explorer/objects/_document.py
src/fmu/sumo/explorer/objects/_search_context.py
src/fmu/sumo/explorer/objects/iteration.py
src/fmu/sumo/explorer/objects/realization.py

Close [#356](https://github.com/orgs/equinor/projects/517/views/22?sliceBy%5Bvalue%5D=liidenee&pane=issue&itemId=89134636&issue=equinor%7Cfmu-sumo%7C356)

feat:add string representation to most used objects

---

src/fmu/sumo/explorer/objects/_search_context.py

New method that returns a map from field value to count; `SearchContext.get_field_values_and_counts` and `SearchContext.get_field_values_and_counts_async`

feat: method to get mapping from field values to counts

---

src/fmu/sumo/explorer/objects/cases.py
src/fmu/sumo/explorer/objects/ensembles.py
src/fmu/sumo/explorer/objects/iterations.py
src/fmu/sumo/explorer/objects/realizations.py

fix: Correction for filters on cases, iterations, ensembles and realizations

---

examples/metrics.ipynb
src/fmu/sumo/explorer/objects/_metrics.py

Closes [#233:sumo ](https://github.com/equinor/sumo/issues/233)

Added async versions of metrics.

---

examples/table-aggregation.ipynb

Forgot to save changes to `examples/table-aggregation.ipynb` before merging https://github.com/equinor/fmu-sumo/pull/421...

chore: rename iteration to ensemble in example notebook

---

src/fmu/sumo/explorer/objects/polygons.py

Closes #446 
Should also resolve failing sumo-uploader tests: https://github.com/equinor/fmu-sumo-uploader/actions/runs/18152049073/job/51664660255

fix: handle parquet polygons
