equinor/fmu-sumo

src/fmu/sumo/uploader/scripts/fm_fmu_uploader.py
tests/test_uploader.py

Perhaps temporary implementation of catch all in FORWARD JOB script on first instance of external call to Sumo, to avoid FMU workflows stop if Sumo has problems.
Not great practice perhaps to catch everything like this, but for now prioritizing that no disruption should be imposed on FMU users while Sumo is in early implementation phase.
Will also solve #59

Catch server errors

---

src/explorer.ipynb
src/fmu/sumo/explorer/_case.py
src/fmu/sumo/explorer/_utils.py

Testing a more flexible and dynamic way of creating buckets on properties.
Instead of a number of methods for creating buckets on various fields, you can now use `get_object_property_values` to get distinct values for a given property within case objects. This can replace the existing methods:
- get_object_tag_name
- get_object_names
- get_object_aggregations
- get_object_time_intervals
`explorer.ipynb` has been updated with documentation and examples.
Getting distinct tag_names within iteration.
```python
tag_names = my_case.get_object_tag_names(
object_type="surface",
iteration_id=0,
)
tag_names = my_case.get_object_property_values(
property="tag_name",
object_type="surface",
iteration_id=0
)
```

Dynamic field bucket method

---

setup.py

The `deprecated` package was missing in setup.py which resulted in an error when testing the Explorer in komodo-bleeding.

add package to required installs in setup.py

---

src/fmu/sumo/explorer/_case.py

After the `get_object_property_values` method was implemented, the "old" methods for creating buckets on various object properties was converted to wrappers for this method and marked as deprecated.
After making some changes to `get_object_property_values` so it accepts lists of values for filtering I forgot to update the old methods using it. Should be ok now.

Explorer parameter names bug

---

requirements.txt
setup.py
src/fmu/sumo/explorer/_case.py
src/testing.py

Komodo release manager requested that we use the `deprecation` package instead of `deprecated` since it's already used by several other komodo packages.
Also did a minor tweak to the way we wrap parameters to lists in the deprecated bucket methods.

use depreaction package instead of deprecated

---

.gitignore
src/fmu/sumo/explorer/_case.py
src/fmu/sumo/explorer/_explorer.py
src/fmu/sumo/explorer/_utils.py

Added `get_objects` method to Explorer class with possibility to filter by case_ids:
```python
from fmu.sumo.explorer import Explorer
sumo = Explorer("dev", interactive=True)
objects = sumo.get_objects(
"surface", 
case_ids=["dba9bba9-7a74-3207-8f96-b08b4ae23d6d"], 
iteration_ids=[0], 
realization_ids=[0]
)
print(len(objects))
```
As requested by the Webviz team, they would like to be able to fetch the objects with less steps. This way they won't have to get the case object before getting the child objects.

Added get_objects method to Explorer class

---

src/fmu/sumo/uploader/scripts/sumo_upload.py

Importing the deprecated ert_shared first in the try clause might trigger deprecation warnings.

Reverse order of ert.shared vs ert_shared imports

---

src/fmu/sumo/explorer/explorer.py

Let `prod` be default when initializing the Explorer.

Let `prod` be default when initializing the Explorer.

---

.gitignore
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/document_collection.py
src/fmu/sumo/explorer/utils.py

New `Case` property: `iterations`. Returns a list of dictionaries with iteration information:
```python
case.iterations
[
{'id': 1, 'name': 'iter-1', 'realizations': 100},
{'id': 0, 'name': 'iter-0', 'realizations': 100}
]
```
Additional stuff:
- Changed the way we get the `len` of a `DocumentCollection` so it returns accurate counts of collections larger than 10 000
- Increased the bucket size when doing term aggregations from 50 -> 2000
- Increased the document batch size from 50 -> 500

Add case.iterations property++

---

src/fmu/sumo/explorer/objects/_child_collection.py
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/polygons_collection.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table_collection.py

Added `Case.get_realizations` method, returns a list of realization ids.
Also added a `uuid` parameter to the `[object_type].filter` methods.

Case realizations and uuid filtering

---

src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_child_collection.py
src/fmu/sumo/explorer/objects/_document_collection.py
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/case_collection.py
src/fmu/sumo/explorer/objects/polygons_collection.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table_collection.py
src/fmu/sumo/explorer/pit.py

New optional `keep_alive` argument in `Explorer` constructor. When argument is in use it will create a new PIT and pass the ID down to child objects to be used when querying the elastic cluster.
I'm not handling the case where the PIT is invalid and the `/search` endpoint returns an error, it will just throw the error returned by the backend. Atm the message is not very meaningful so we should maybe look into returning the original elastic error message.

Add point in time logic

---

src/fmu/sumo/explorer/objects/table.py
tests/test_aggregated_table.py
tests/test_table.py

Ensure that csv objects are read as csv, pyarrow.parquet seems to be able to read these, causing havoc

Fix table read

---

src/fmu/sumo/explorer/objects/table.py

Closes #181.
Below snippet is copied from https://docs.python.org/3/howto/logging.html. Based on that I would argue it is better in this case to use default Python behavior in this case (i.e. not impose a `NullHandler`).
> If for some reason you don’t want these messages printed in the absence of any logging configuration, you can attach a do-nothing handler to the top-level logger for your library. This avoids the message being printed, since a handler will always be found for the library’s events: it just doesn’t produce any output. If the library user configures logging for application use, presumably that configuration will add some handlers, and if levels are suitably configured then logging calls made in library code will send output to those handlers, as normal.
> 
> A do-nothing …

Remove `logging.NullHandler`

---

requirements/requirements.txt

Can not have requirement using direct url when publishing to PyPi.

install wrapper from pypi

---

src/fmu/sumo/explorer/objects/case.py

The `case.iterations` property was still using `fmu.iteration.id`, this PR changes updates it to use `fmu.iteration.uuid`.
This could cause issues if we have some outdated metadata missing the `uuid` field, not sure if this will be a problem.

Update case.iterations to use uuid instead of id

---

docs/conf.py
requirements/requirements_docs.txt

`sphinx-togglebutton` is the source of some vulnerabilities reported by snyk.
Can't see that it is actually used anywhere so trying to just remove it.

remove sphinx-togglebutton

---

README.md
docs/explorer.rst
src/fmu/sumo/explorer/objects/cube.py

Handle importing `OpenVDS` on MacOS and issue warning. Using methods/properties from the `Cube` class that uses `OpenVDS` will still raise exceptions.
I had to remove the type hints for `Cube` properties `openvds_handle` and `openvds_handle_async` as this raises exceptions on MacOS and I didn't find a way to do conditional type hinting. Open to suggestions for alternative solutions to this.

Handle missing OpenVDS, add warnings

---

src/fmu/sumo/utilities/sim2sumo.py
tests/data/reek/realization-0/iter-0/fmuconfig/output/global_variables_w_eclpath_and_extras.yml
tests/test_utility_sim2sumo.py

Change code for sim2sumo utility such that no section sim2sumo in config file give upload of some standard types from simulator. These are for the time being summary, rft, and relative permeability (aka satfunc in sim2sumo speak)
With this change all the user wil have to do is add FORWARD_MODEL SIM2SUMO, and he or she will imedeately start uploading simulator results to sumo.
Also defaults to uploading arrow files, now user will have to specify arrow: false to not use arrow, then it changes to csv files

Always sim2sumo

---

examples/explorer.ipynb
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/dictionary.py
src/fmu/sumo/explorer/objects/dictionary_collection.py

Add support for retrieving files with `class:dictionary`.
```python
dicts = my_case.dictionaries.filter(
name="parameters",
iteration="iter-0",
realization=0
)
params = dicts[0]
```
```python
dicts = my_case.dictionaries.filter(
name="parameters",
iteration="iter-4", 
aggregation="collection",
)
param_names = dicts.tagnames
dicts = dicts.filter(tagname=param_names[0])
params = dicts[0]
```
```python
params.parse()
```

Explorer dictionary support

---

setup.py

Snyk reports a vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2023-4863
Seems to be because Python <=3.7 ends up with Pillow@9.5.0. Python >=3.8 ends up with a non vulnerable Pillow@10.0.1.
Updating our project config should hopefully remove the Snyk report.
Also, komodo stable runs on Python 3.8 + Python 3.7 has reached EOL.

set minimum required python version to 3.8

---

src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_document_collection.py
src/fmu/sumo/explorer/objects/case_collection.py
src/fmu/sumo/explorer/objects/cube_collection.py
src/fmu/sumo/explorer/objects/dictionary_collection.py
src/fmu/sumo/explorer/objects/polygons_collection.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table_collection.py
src/fmu/sumo/explorer/pit.py

`DocumentCollection` can now be treated as an iterator and async iterator, enabling async iteration with the `async for .. in ..` syntax.
Some improvements in `pit` functionality:
- Use the updated pit id
- Pass `pit` to case returned by `Explorer.get_case_by_uuid` (bug fix) 
We are not deleting the `pit`, which is recommended. This is currently not possible because `SumoClient.delete` does not take params which is needed to call the `DELETE /api/v1/pit` endpoint. 
Closes #228

implement __iter__ and __aiter__ in DocumentCollection

---

README.md
src/fmu/sumo/explorer/objects/_child_collection.py
src/fmu/sumo/explorer/objects/surface_collection.py

Fixes #248 
* Update README example code to work "out of the box"
* Fix filtering of bool properties. Probably possible to do it more elegantly...

update README and fix filtering on bool properties

---

src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_document_collection.py
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/case_collection.py

Done as part of the  `_next_batch` method of class DocumentCollection.

Generate case summaries based on aggregations.

---

src/fmu/sumo/explorer/objects/table.py
tests/test_objects_table.py

Solve #267 
The `to_pandas` implementation is inconsistently implemented. In `Table`, it is implemented as a property. While similar looking `to_arrow` is a method. Also, the name indicates that this should be a function. `to_pandas` is also a function in other object classes, e.g. `Polygons.to_pandas()`.
🟩 This PR restructures the tests somewhat and adds tests for methods/functions that was not tested.
🟩 This PR changes `Table.to_pandas` from a property to a function. ⚠️ **Breaking change** ⚠️ 
Old pattern (discontinued with this PR):
```python
df = mytable.to_pandas
```
New pattern (introduced with this PR):
```python
df = mytable.to_pandas()
```

267 to pandas as function

---

src/fmu/sumo/explorer/objects/polygons.py
src/fmu/sumo/explorer/objects/table.py
tests/test_objects_table.py

This PR discontinues three deprecated methods:
- `Polygons.to_dataframe()`
- `Table.dataframe()`
- `Table.arrowtable()`
All three methods have been flagged as deprecated for 6+ months.

Discontinue deprecated methods

---

.github/workflows/run_tests_access_drogon_manage_login.yaml
.github/workflows/run_tests_access_drogon_read_login.yaml
.github/workflows/run_tests_access_drogon_write_login.yaml
.github/workflows/run_tests_access_no_access_login.yaml
tests/data/test_case_080/case2.json
tests/test_access/README.md
tests/test_access/tst_access_drogon_manage_login.py
tests/test_access/tst_access_drogon_read_login.py
tests/test_access/tst_access_drogon_write_login.py
tests/test_access/tst_access_no_access_login.py

[https://github.com/equinor/fmu-sumo/issues/283](https://github.com/equinor/fmu-sumo/issues/283)

Add testing of SUMO access using different user identity on each test

---

.github/workflows/run_tests_access_drogon_manage_login.yaml
.github/workflows/run_tests_access_drogon_manage_sharedkey.yaml
.github/workflows/run_tests_access_drogon_read_login.yaml
.github/workflows/run_tests_access_drogon_read_sharedkey.yaml
.github/workflows/run_tests_access_drogon_write_login.yaml
.github/workflows/run_tests_access_drogon_write_sharedkey.yaml
.github/workflows/run_tests_access_no_access_login.yaml

https://github.com/orgs/equinor/projects/517/views/2?sliceBy%5Bvalue%5D=roywilly&pane=issue&itemId=51867183

Automated access tests: Shorten names for visibility in Github Actions

---

README.md
docs/explorer.rst

Move from readme file to ReadTheDocs (avoids duplication. Add PIT info and example

---

.github/workflows/build_docs.yaml
.github/workflows/publish_release.yaml
.github/workflows/run_tests.yaml
.github/workflows/run_tests_access_drogon_manage_login.yaml
.github/workflows/run_tests_access_drogon_manage_sharedkey.yaml
.github/workflows/run_tests_access_drogon_read_login.yaml
.github/workflows/run_tests_access_drogon_read_sharedkey.yaml
.github/workflows/run_tests_access_drogon_write_login.yaml
.github/workflows/run_tests_access_drogon_write_sharedkey.yaml
.github/workflows/run_tests_access_no_access_login.yaml
tests/test_access/README.md

This should remove these warnings:
"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/login@v1, actions/checkout@v3, actions/setup-python@v3."
The tests are failing on aggregations, this is unrelated to this PR.

Update github actions to stop using old node version

---

src/fmu/sumo/explorer/objects/_child_collection.py
src/fmu/sumo/explorer/objects/cube_collection.py
src/fmu/sumo/explorer/objects/dictionary_collection.py
src/fmu/sumo/explorer/objects/polygons_collection.py
src/fmu/sumo/explorer/objects/surface_collection.py
src/fmu/sumo/explorer/objects/table_collection.py

[_Link to the issue resolved by this PR._](https://github.com/orgs/equinor/projects/517/views/2?sliceBy%5Bvalue%5D=adnejacobsen&pane=issue&itemId=43076462)
Add `content` parameter to `filter` methods and add a `contents` property for retrieving unique content values in a collection.

Add support for content filtering

---

pyproject.toml

[Recommended practice to use the classifier when using standard licenses.](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license)

add license classifier in pyproject.toml

---

.github/workflows/run_tests.yaml
pyproject.toml
src/fmu/sumo/explorer/objects/cube.py
tests/test_explorer.py

https://github.com/equinor/fmu-sumo/issues/306

OpenVDS not supported on python 3.12

---

docs/explorer.rst

#306 
Updating docs following #307

DOC: Notify OpenVDS not available on Python 3.12

---

tests/test_access/tst_access_drogon_manage_login.py
tests/test_access/tst_access_drogon_read_login.py
tests/test_access/tst_access_drogon_write_login.py

Adapt nightly tests to new aggregation rules; must have more than 1 realization

---

tests/test_access/tst_access_drogon_read_login.py

See if this solves the issue with running fast aggregation on surfaces after latest server-side change to require 2 objects minimum

Fix tests: use 2 similar surfaces for fast aggregation

---

src/fmu/sumo/explorer/objects/surface_collection.py

Only import what we need from xtgeo

Only import what we need from xtgeo

---

src/fmu/sumo/explorer/objects/table.py

Fix table.to_arrow() for data.format=parquet

---

examples/metrics.ipynb
src/fmu/sumo/explorer/objects/__init__.py
src/fmu/sumo/explorer/objects/_metrics.py
src/fmu/sumo/explorer/objects/_search_context.py
tests/test_access/tst_access_drogon_affiliate_login.py
tests/test_access/tst_access_drogon_manage_login.py
tests/test_access/tst_access_drogon_read_login.py
tests/test_access/tst_access_drogon_write_login.py
tests/test_access/tst_access_no_access_login.py
tests/test_explorer.py

N/A
Adds various metrics aggregation to search contexts, specifically, "min", "max", "avg", "sum", "stats", "extended_stats",
"percentiles", "value_count" and "cardinality". These are accessed through the `metrics` member on class `SearchContext`. See examples in `examples/metrics.ipynb`.

Added various metrics to SearchContext.

---

examples/table-aggregation.ipynb
src/fmu/sumo/explorer/objects/polygons.py
src/fmu/sumo/explorer/objects/table.py

Also, do a little cleanup based on flake8 findings.
N/A
Move some "expensive" imports from top-level of files into the methods where they are needed.
Also (incidentally/accidentally): added a new example notebook showing performance gains when using split tables for aggregation.

Defer 'expensive' imports until they are needed.

---

src/fmu/sumo/explorer/cache.py
src/fmu/sumo/explorer/objects/__init__.py
src/fmu/sumo/explorer/objects/_search_context.py
src/fmu/sumo/explorer/objects/cases.py
src/fmu/sumo/explorer/objects/cpgrid.py
src/fmu/sumo/explorer/objects/cpgrid_property.py
src/fmu/sumo/explorer/objects/iterations.py
src/fmu/sumo/explorer/objects/realizations.py
tests/test_explorer.py

N/A
- adds class `CPGrid`
- adds class `CPGridProperty`
- adds accessors `grids` and `grid_properties` to class `SearchContext` (similar to existing accessors `surfaces`, `tables`, etc.)

Add support for grids and grid properties

---

src/fmu/sumo/explorer/objects/_search_context.py

Bug reported by Webviz team on slack.
Insert missing `await` in a call to async method.

fix: need await when calling async method.

---

src/fmu/sumo/explorer/explorer.py
src/fmu/sumo/explorer/objects/_search_context.py

N/A
Add two new methods, `aggregation()` and `aggregation_async()`. These try to retrieve an existing aggregation that matches the current context; if that doesn't work, they create a new aggregation and returns that.
Add two new constructor arguments to the `Explorer` constructor, so that users can supply their own instances of `https.Client` and/or `https.AsyncClient`.

feat: add aggregation and aggregation_async methods

---

src/fmu/sumo/explorer/objects/_search_context.py

#370
Use async calls instead of sync calls.

fix: missing async for a length check and in get_iteration_by_uuid_async

---

src/fmu/sumo/explorer/objects/cases.py
src/fmu/sumo/explorer/objects/iterations.py
src/fmu/sumo/explorer/objects/realizations.py

The previous selector for the `SearchContext` part of `Cases` actually selected all children of the cases, and similarly for `Iterations` and `Realizations`. As an example, calling `len()` on an instance of `Cases` would actually return the total number of objects (including the `case` object) for all cases in the list, rather than the number of cases.

fix: correct selectors for cases, iterations and realizations

---

src/fmu/sumo/explorer/objects/_child.py
src/fmu/sumo/explorer/objects/_search_context.py
src/fmu/sumo/explorer/objects/cpgrid.py
src/fmu/sumo/explorer/objects/cpgrid_property.py

`cpgrid` and `cpgrid_property` objects are supposed to be linked via the attributes `data.geometry.relative_path` (`cpgrid_property`)  and `file.relative_path` (`cpgrid`), with the additional requirement that the objects need to be of the correct classes and that case, iteration and realization should also match.
This requires that the sumo upload is correctly configured, which it mostly isn't. At some later time, it may be possible to update the objects already stored in Sumo and use just this linkage mechanism.
The alternative linkage uses `data.tagname` (`cpgrid_property`) and `data.name` (`cpgrid`), with the same addiotional requirements as above.

fix: improved grid property linkage

---

src/fmu/sumo/explorer/objects/_child.py
src/fmu/sumo/explorer/objects/_document.py
src/fmu/sumo/explorer/objects/_search_context.py
src/fmu/sumo/explorer/objects/case.py
src/fmu/sumo/explorer/objects/iteration.py
src/fmu/sumo/explorer/objects/realization.py

The idea of injecting properties into various class in `fmu.sumo.explorer` was _almost_ a good one, but it confused `pylint` and various IDE integrations.
This PR replaces the injected properties with explicitly coded properties.

fix: Replace injected properties with explicitly defined properties.

---

.github/workflows/run_tests.yaml

The access tests were moved to another repo.
Don't see a reason to run these Explorer specific tests nightly, on PR should be enough?

chore: disable nightly test runs

---

src/fmu/sumo/explorer/objects/_search_context.py
src/fmu/sumo/explorer/objects/iteration.py
src/fmu/sumo/explorer/objects/realization.py

When asked for "iteration" and realization objects, first try to get them from sumo. If the objects do not exist, synthesize them child objects.
Closes #388

fix: return realization and iteration objects if they exist

---

src/fmu/sumo/explorer/objects/_search_context.py

- Realization objects only.
- For table aggregation, only include realizations that contain the columns specified.

fix: Ensure that only appropriate objects are used as input to aggregation

---

src/fmu/sumo/explorer/objects/_search_context.py

Parameter aggregation uses operation=collection, but does not specify columns. Adjust `_verify_aggregation_operation_async` to allow for this. 
The sync version (`_verify_aggregation_operation`) already does this correctly.

fix: correction to async version of verify_aggregation_operation 

---

src/fmu/sumo/explorer/objects/_child.py
src/fmu/sumo/explorer/objects/_document.py
src/fmu/sumo/explorer/objects/_search_context.py
src/fmu/sumo/explorer/objects/ensemble.py
src/fmu/sumo/explorer/objects/iteration.py
src/fmu/sumo/explorer/objects/realization.py

Close https://github.com/equinor/fmu-sumo/issues/433
- For search context __str__ and  __repr__ will behave the same
- For some classes, the __str__ is not properly setup. For example in the `Ensemble` class, the __str__ is not specified so it is inherited from the parent class. But it is lacking ensemble name.

fix: fix search context by making __str__ and __repr__ behave the same

---

src/fmu/sumo/explorer/objects/_search_context.py

Linked issue: https://github.com/equinor/sumo-fmu-aggregation-service/issues/401
In explorer, we check if there is a filter on realization for table and parameter aggregation, if there is, raise an exception. 
We raise an exception:
`Exception: Filtering on realization is not allowed for table and parameter aggretation.`

feat: raise exception if filter on realization for table and parameter aggregation

---

src/fmu/sumo/explorer/objects/_metrics.py

This can be used for a quick check for changes in document (blob) content by getting a checksum over `_sumo.blob_md5.keyword` or `file.checksum_md5.keyword`.
Suggested by Sigurd Pettersen.

feat: added aggregation for fnv-1a checksum over specified field.

---

src/fmu/sumo/explorer/objects/_search_context.py

fix: do not do regular expression expansion of patterns in batch_aggregate/batch_aggregate_async; the user needs to do this explicitly.
fix: limit batch_aggregate/batch_aggregate_async to max 1000 columns at a time.

fix: adjustments to batch aggregation
